Add QMPlay2 icon
EliverLara/candy-icons pull request #562
Opened 2024-04-12 05:39 UTC by DiabloCRP

2024-04-12 15:42 UTC, DiabloCRP commented
[5aff5b2](https://github.com/EliverLara/candy-icons/pull/562/commits/5aff5b20ce50cdaba3b38fd090ad6de00479c510) Extra nodes are removed, curves are aligned
[2bd4f74](https://github.com/EliverLara/candy-icons/pull/562/commits/2bd4f746bb4aa18ad53b7db0cc7a6d6c7684399e) relative to https://github.com/EliverLara/candy-icons/issues/504

2024-04-13 17:28 UTC, DiabloCRP commented
Github doesn't show some gradients 🤪, but they are there and they work

![ksnip_20240413-202555](https://github.com/EliverLara/candy-icons/assets/160734047/6e99c684-37d2-4081-a4a8-af17c26125d7)

2024-04-13 18:45 UTC, EliverLara commented
I haven't reviewed all your changes, but regarding to your last two commits if you want to add custom folder colors it would be better to open a pull request in [sweet-folders](https://github.com/EliverLara/Sweet-folders/pulls) repo, on the other hand the additions I've checked so far looks really good! and finally as a recommendation it would be better if you open different pull request for different changes you make so it will be easy for me to review and merge them. 

Thanks for contributing!

2024-04-13 19:03 UTC, DiabloCRP commented
> but regarding to your last two commits

Rolled back folders color responsive

> finally as a recommendation it would be better if you open different pull request for different changes

I hope this won't be necessary for these changes? 🙄

2024-04-13 19:10 UTC, EliverLara approved these changes

2024-04-13 19:10 UTC, EliverLara approved these changes

2024-04-13 19:11 UTC, EliverLara approved these changes

2024-04-13 19:51 UTC, EliverLara approved these changes

2024-04-13 19:52 UTC, EliverLara approved these changes

2024-04-13 20:53 UTC, EliverLara requested changes

2024-04-13 20:53 UTC, EliverLara commented on places/48/folder-documents.svg
For this folders it would be better to keep the current color

2024-04-13 20:53 UTC, EliverLara commented on places/48/folder-download.svg
For this folders it would be better to keep the current color

2024-04-13 20:53 UTC, EliverLara commented on places/48/folder-games.svg
For this folders it would be better to keep the current color

2024-04-13 20:53 UTC, EliverLara commented on places/48/folder-music.svg
For this folders it would be better to keep the current color

2024-04-13 20:53 UTC, EliverLara commented on places/48/folder-pictures.svg
For this folders it would be better to keep the current color

2024-04-13 20:53 UTC, EliverLara commented on places/48/folder-publicshare.svg
For this folders it would be better to keep the current color and the current design

2024-04-13 20:53 UTC, EliverLara commented on places/48/folder-recent.svg
For this folders it would be better to keep the current color

2024-04-13 20:53 UTC, EliverLara commented on places/48/folder-templates.svg
For this folders it would be better to keep the current color

2024-04-13 20:53 UTC, EliverLara commented on places/48/folder-videos.svg
For this folders it would be better to keep the current color

2024-04-13 20:53 UTC, EliverLara commented on places/48/user-desktop.svg
This one looks great!

2024-04-13 21:07 UTC, DiabloCRP commented on places/48/folder-publicshare.svg
Changing the color of all folders to the default is not a problem and can be completed within 5-10 minutes. But I used the same colors that are currently used in your repository. Decide whether to change or not. If yes, I’ll do it now.
![ksnip_20240414-000711](https://github.com/EliverLara/candy-icons/assets/160734047/6d469b36-1609-41cf-a5bb-770203c8defe)

2024-04-13 21:20 UTC, EliverLara commented on places/48/folder-publicshare.svg
They look so different the current colors and the one you use:

![Captura desde 2024-04-13 15-17-36](https://github.com/EliverLara/candy-icons/assets/9838260/c923086a-6014-4494-86f3-84e98c5ba0bf)

I thought it was the main change(changing colors) in those files, if not, may I know what are the changes in those folders?

2024-04-13 21:24 UTC, DiabloCRP commented on places/48/folder-publicshare.svg
This is what I said above: Github doesn't show some gradients, but they are there and they work
![ksnip_20240414-002342](https://github.com/EliverLara/candy-icons/assets/160734047/3eb0a4a0-17c6-4f54-bd1a-89c71ce75ae5)

2024-04-13 21:30 UTC, EliverLara commented on places/48/folder-publicshare.svg
They look different:

Original candy-icons files:

![Captura desde 2024-04-13 15-15-32](https://github.com/EliverLara/candy-icons/assets/9838260/18ecceb4-726f-40a6-80fa-4fdb65d402c5)

Files in your commit:

![Captura desde 2024-04-13 15-14-59](https://github.com/EliverLara/candy-icons/assets/9838260/93b6968f-75bd-4f7b-ab23-7c300202cb83)

2024-04-13 21:34 UTC, DiabloCRP commented on places/48/folder-publicshare.svg
There were a lot of things like this: 
![ksnip_20240414-002810](https://github.com/EliverLara/candy-icons/assets/160734047/07083d93-76e3-4269-9606-529a310bea29)
In the end, I simply took the previous form, smoothed out minor errors and applied a translucent mask - this, if necessary, allows you to change the color of the folder in two clicks.
![ksnip_20240414-002924](https://github.com/EliverLara/candy-icons/assets/160734047/2e9eb98a-4592-4c3d-abbb-bc13da5137bf)

2024-04-13 21:39 UTC, DiabloCRP commented on places/48/folder-templates.svg
> Files in your commit:
Looks weird. I wonder how they are displayed correctly for me.
Got it. Wll fix it now. Should I make it the default color, or what it was before?

2024-04-13 21:40 UTC, DiabloCRP commented on places/48/folder-publicshare.svg
»» Files in your commit:««
Looks weird. I wonder how they are displayed correctly for me.
Got it. Wll fix it now. Should I make it the default color, or what it was before?

2024-04-13 21:45 UTC, EliverLara commented on places/48/folder-publicshare.svg
> Should I make it the default color, or what it was before?

I'd like to keep the original colors

2024-04-13 22:23 UTC, DiabloCRP commented on places/48/folder-publicshare.svg
> 
> I'd like to keep the original colors

Done

2024-04-13 23:18 UTC, EliverLara commented on places/48/folder-publicshare.svg
Thanks, It looks better now!  I'll check/test some things and I'll be merging it ASAP thank you so much!

2024-04-20 20:04 UTC, EliverLara approved these changes

2024-04-20 20:07 UTC, merged

2024-04-20 20:10 UTC, EliverLara commented
I've just merge your changes @DiabloCRP, Thank you so much for your contributions!